# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FieldLink
                                 A QGIS plugin
 This plugin displays geodata from iDAI.field / Field Desktop in QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-25
        copyright            : (C) 2024 by Lisa Steinmann
        email                : lisa.steinmann@dainst.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FieldLink class from file FieldLink.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fieldlink import FieldLink
    return FieldLink(iface)
